### ISSUE TITLE
With Level Skip on, the game continues after game over.

### ISSUE THREAD

**Issue by wbovela** [mwenge/iridisalpha#1]
(PS: I realise you've probably not written the Hokuto Force patch but I wanted to note it anyway)

Not sure if this is intended, but when I set (just) level skip to Y the game seems to continue after pressing fire on the highscore table screen.

Pressing Q in game will end and properly restart the game at the first wave.

**Comment by mwenge** [comment]
Can you provide some more detail here? I'm not sure where you set level skip to Y - that may be in the cracked version of the game. I would have removed stuff like that for this version.

**Comment by wbovela** [comment]
This issue probably doesn't belong here at all. I posted the issue whilst working on a youtube video on how to play Iridis Alpha. To get footage for my video I used the Hokuto Force version and their level skip option. Somehow I must have understood that you had incorporated some of the fixes Hokuto Force had included in their cracked version of the game. I contacted them, but they said they no longer had the source code. It does contain a bug where the game doesn't reset when you use the level skip, but that is inconsequential.

Great work on the 'difficulty cliff' removal. It really works well and improves the game experience if you ask me.

**Comment by wbovela** [comment]
I think I was a little frustrated over the fact that Hokuto Force published their crack and then discarded the code. When I asked them about it they were less than amused. 

I had noticed that re-occuring of past enemies as well. I figured it was caused by some initialisation being missed at some point. Fixing that would be another improvement to the original. Jeff would approve I assume :)
